---


- name: Run localhost Configuration
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    - mysql_root_password: ncrsb
  tasks:


  - name: print out the hostname of target
    command: hostname

  - name: ensure aptitude is installed
    command: apt-get -y install aptitude

  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes

  - name: add apt key for nodesource
    apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

  - name: add repo for nodesource
    apt_repository:
          repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
          update_cache: yes

  - name: install nodejs
    apt: name=nodejs

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    apt:
     name: "{{ item }}"
     state: installed
     update_cache: yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
     - docker-ce
     - git

  - name: Specify MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password}}' vtype='password'
    become: true

  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password}}' vtype='password'
    become: true

  - name: MySQL | install mysql packages
    apt: pkg={{ item }} state=installed
    become: true
    with_items:
     - mysql-client
     - mysql-common
     - mysql-server
     - python-mysqldb

  - name: Start the MySQL service
    action: service name=mysql state=started
